### PR TITLE
[FIX] add more repr methods

### PR DESCRIPTION
**Pull request by burtenshaw**
This PR adds further repr methods as strings that were wrongly generators

### CODE REVIEW

**Review by frascuchon — COMMENTED** [review]
Maybe it would be nice adding some minimal tests checking a basic repr. I've already created one for [records](https://github.com/argilla-io/argilla-python/blob/fix/add-more-repr-methods/tests/unit/test_resources/test_records.py#L8)

**Comment by burtenshaw** [comment]
@frascuchon Test added

**Comment by frascuchon** [comment]
> @frascuchon Test added

There are failed tests on Python 3.11 https://github.com/argilla-io/argilla-python/actions/runs/9064161679/job/24901760260#step:7:94. Enums?

**Comment by frascuchon** [comment]
> > @frascuchon Test added
> 
> There are failed tests on Python 3.11 https://github.com/argilla-io/argilla-python/actions/runs/9064161679/job/24901760260#step:7:94. Enums?

Fixed https://github.com/argilla-io/argilla-python/pull/166/commits/b6c937aa3456a39005beac3179eb875aecba5f34

**Review by frascuchon — APPROVED** [review]

**Pull request merged**
